export let featuredCharacters: string[] = [
    'wolverine',
    'spider-man',
    'iron man',
    'thanos',
    'deadpool',
    'Deadpool (X-Men: Battle of the Atom)',
    'hulk',
    'black widow',
    'thor',
    'thor (goddess of thunder)',
    'Thor (Marvel War of Heroes)',
    'cyclops',
    'Cyclops (X-Men: Battle of the Atom)',
    'apocalypse',
    'cable',
    'daredevil (ultimate)',
    'gamora',
    'Gamora (Marvel War of Heroes)',
    'storm',
    'jean grey',
    'magneto (age of apocalypse)',
    'mystique',
    'Ant-Man (Eric O\'Grady)',
    'avengers',
    'BEAST',
    'cable',
    'captain america',
    'Captain Marvel (Carol Danvers)',
    'black panther',
    'black cat',
    'colossus',
    'doctor doom',
    'doctor strange',
    'drax',
    'falcon',
    'gambit',
    'Ghost Rider (Daniel Ketch)',
    'groot',
    'human torch',
    'invisible woman',
    'james howlett',
    'juggernaut',
    'maria hill',
    'nebula',
    'Norrin Radd',
    'professor x',
    'punisher',
    'Rocket Raccoon',
    'Rogue',
    'scarlet witch',
    'scarlet witch (ultimate)',
    'silver surfer',
    'thing',
    'valkyrie (ultimate)',
    'Venom (Mac Gargan)',
    'x-23',
    'x-men'
]